export enum TraitType {
  BACKGROUND = 'BACKGROUND',
  BODY = 'BODY',
  FACE = 'FACE',
  MOUTH = 'MOUTH',
  EYES = 'EYES',
  CLOTHES = 'CLOTHES',
  GLASSES = 'GLASSES',
  HAT = 'HAT',
  EARRING = 'EARRING',
  NECKLACE = 'NECKLACE',
}
